version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    image: node:18-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["node", "server.js"]
    ports:
      - "5500:5500"
    environment:
      - OLLAMA_API=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data:
